version: '3'
services:
    zookeeper:
        image: wurstmeister/zookeeper
        # network_mode: "host"
        restart: always
        ulimits:
            nproc: 65535
            nofile:
                soft: 65535
                hard: 65535
        ports:
          - "2181:2181"

    kafka:
        image: wurstmeister/kafka
        # network_mode: "host"
        depends_on:
            - zookeeper
        restart: always
        environment:
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: OUTSIDE://15.160.17.195:9092,INSIDE://:19092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_LISTENERS: OUTSIDE://0.0.0.0:9092,INSIDE://:19092
            KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
            KAFKA_CREATE_TOPICS: viidPerson:1:1,viidFace:1:1,viidMotorVehicle:1:1
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ulimits:
            nproc: 65535
            nofile:
                soft: 65535
                hard: 65535
        ports:
           - "9092:9092"

    kafka-connector:
        build: ./kafka-connector
        restart: always
        # network_mode: "host"
        depends_on:
            - kafka
        environment:
            CONNECT_BOOTSTRAP_SERVERS: kafka:9092
            MONGO_HOST: 15.160.17.195
            MONGO_PORT: 27017
        ports:
           - "8083:8083"

